services:
  - type: web
    name: roblox-irc-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envs:
      - key: PORT
        value: 10000
      - key: ENABLE_IRC
        value: "false"
      - key: IRC_HOST
        value: irc.libera.chat
      - key: IRC_PORT
        value: "6697"
      - key: IRC_NICK
        value: roblox_bot
      - key: IRC_CHANNELS
        value: "#general,#random"
